### ISSUE TITLE
Default root login.

### ISSUE THREAD

**Issue by cedrox** [scaleway/image-app-wordpress#7]
Hello, 
I cannot understand what's the process of first login thanks to ssh. Is there a default password ? 
Digital Ocean send it by mail. You ask to setup it from serial console but I cannot figure out how to do it ? Can you explain ?

**Comment by cedrox** [comment]
Ok, sorry it's been long time that I didn't work on Linux. I generate a new key and add it to the console but It's was finally the first one which work as expected... 
PS : Don't forget to restart your server if you add new key...

**Comment by edouardb** [comment]
You can find the documentation to connect your server at https://www.scaleway.com/docs/create-and-connect-to-your-server/
