### ISSUE TITLE
Mail settings

### ISSUE THREAD

**Issue by cedrox** [scaleway/image-app-wordpress#8]
Is there any specific setup to enable mail on Wordpress image ?
Thanks

**Comment by brmzkw** [comment]
Did you configure the security groups of your server?

https://www.scaleway.com/faq/server/#-I-cannot-send-any-email

**Comment by cedrox** [comment]
Thanks to point out this faq item. I create a security group, open SMTP, assign it to my server and restart but there is still no way to get a mail. I am not sure that Wordpress use SMTP by default...

**Comment by brmzkw** [comment]
@moul you marked this issue as bug. Did you reproduce it?

**Comment by moul** [comment]
I didn't tested yet, but this issue seems to be a blocker, so I flagged it as a bug

**Comment by szepeviktor** [comment]
This plugin sets up SMTP by one short string, an URI:
https://wordpress.org/plugins/smtp-uri/

`smtp://localhost` is for local SMTP.

**Comment by moebis** [comment]
scaleway asked me to open an issue here, but it looks like someone already did. Anyways, here is a quick fix:

just do "apt-get install mailutils" select internet site (and use your root domain name when asked), then in /etc/postfix/main.cf, change inet_interfaces from "all" to "localhost" or "loopback-only", then "service postfix restart" and you should have a working MTA on your wordpress box.

**Comment by cedrox** [comment]
Sorry, I tried both "localhost" or "loopback-only" without success.
My form message turn like it work but no mail.
have you got any tip for debugging ? How can I see pickup queue on linux ?
Thanks

**Comment by edouardb** [comment]
Can you try to run `dpkg-reconfigure postfix` and retry?

**Comment by szepeviktor** [comment]
> How can I see pickup queue on linux ?

http://www.postfix.org/postqueue.1.html

**Comment by moebis** [comment]
I believe you also have to open the SMTP port (25?) on the scaleway firewall/gateway, or port policies (whatever they call it).

**Comment by cedrox** [comment]
Hello, I reconfigure postfix; open TCP outbound on 0.0.0.0/0 port 25, restart... Nada, ...
I am on a dev instance, on a sub domain but it should work...
Thanks you for your time !

Here my log error

$ /var/log# cat mail.log
Sep 22 20:15:36 redsen-wordpress01 postfix/master[4423]: terminating on signal 15
Sep 22 20:20:38 redsen-wordpress01 postfix/master[25627]: daemon started -- version 2.11.1, configuration /etc/postfix
Sep 22 20:28:12 redsen-wordpress01 postfix/pickup[25631]: B5EAB2A0E07: uid=33 from=<www-data>
Sep 22 20:28:12 redsen-wordpress01 postfix/cleanup[25662]: B5EAB2A0E07: message-id=<9f4f843dbd0791624a2782cea76df005@dev.redsen-consulting.com>
Sep 22 20:28:12 redsen-wordpress01 postfix/qmgr[25632]: B5EAB2A0E07: from=<www-data@redsen-consulting.com>, size=705, nrcpt=1 (queue active)
Sep 22 20:28:12 redsen-wordpress01 postfix/local[25664]: B5EAB2A0E07: to=<cfolliot@redsen-consulting.com>, relay=local, delay=0.12, delays=0.06/0.01/0/0.05, dsn=5.1.1, status=bounced (unknown user: "cfolliot")
Sep 22 20:28:12 redsen-wordpress01 postfix/cleanup[25662]: CFD232A15B6: message-id=<20150922202812.CFD232A15B6@redsen-wordpress01>
Sep 22 20:28:12 redsen-wordpress01 postfix/bounce[25665]: B5EAB2A0E07: sender non-delivery notification: CFD232A15B6
Sep 22 20:28:12 redsen-wordpress01 postfix/qmgr[25632]: CFD232A15B6: from=<>, size=2585, nrcpt=1 (queue active)
Sep 22 20:28:12 redsen-wordpress01 postfix/qmgr[25632]: B5EAB2A0E07: removed
Sep 22 20:28:12 redsen-wordpress01 postfix/local[25664]: CFD232A15B6: to=<www-data@redsen-consulting.com>, relay=local, delay=0.08, delays=0.04/0/0/0.04, dsn=2.0.0, status=sent (delivered to mailbox)
Sep 22 20:28:12 redsen-wordpress01 postfix/qmgr[25632]: CFD232A15B6: removed
Sep 22 20:46:33 redsen-wordpress01 postfix/master[2228]: daemon started -- version 2.11.1, configuration /etc/postfix
Sep 22 20:47:50 redsen-wordpress01 postfix/pickup[2239]: ACBAC2A1A18: uid=33 from=<www-data>
Sep 22 20:47:50 redsen-wordpress01 postfix/cleanup[2618]: ACBAC2A1A18: message-id=<7888661fb0a3bae027b3b423584500e8@dev.redsen-consulting.com>
Sep 22 20:47:50 redsen-wordpress01 postfix/qmgr[2240]: ACBAC2A1A18: from=<www-data@redsen-consulting.com>, size=701, nrcpt=1 (queue active)
Sep 22 20:47:50 redsen-wordpress01 postfix/local[2620]: ACBAC2A1A18: to=<cfolliot@redsen-consulting.com>, relay=local, delay=0.18, delays=0.1/0.03/0/0.05, dsn=5.1.1, status=bounced (unknown user: "cfolliot")
Sep 22 20:47:50 redsen-wordpress01 postfix/cleanup[2618]: CC1512A1A1A: message-id=<20150922204750.CC1512A1A1A@redsen-wordpress01>
Sep 22 20:47:50 redsen-wordpress01 postfix/bounce[2621]: ACBAC2A1A18: sender non-delivery notification: CC1512A1A1A
Sep 22 20:47:50 redsen-wordpress01 postfix/qmgr[2240]: CC1512A1A1A: from=<>, size=2581, nrcpt=1 (queue active)
Sep 22 20:47:50 redsen-wordpress01 postfix/qmgr[2240]: ACBAC2A1A18: removed
Sep 22 20:47:50 redsen-wordpress01 postfix/local[2620]: CC1512A1A1A: to=<www-data@redsen-consulting.com>, relay=local, delay=0.12, delays=0.04/0/0/0.08, dsn=2.0.0, status=sent (delivered to mailbox)
Sep 22 20:47:50 redsen-wordpress01 postfix/qmgr[2240]: CC1512A1A1A: removed
Sep 22 20:54:33 redsen-wordpress01 postfix/master[2170]: daemon started -- version 2.11.1, configuration /etc/postfix
Sep 22 20:56:20 redsen-wordpress01 postfix/pickup[2181]: 316CF2A1A19: uid=33 from=<www-data>
Sep 22 20:56:20 redsen-wordpress01 postfix/cleanup[2788]: 316CF2A1A19: message-id=<349c4435dee7f522d75b36d5032c5102@dev.redsen-consulting.com>
Sep 22 20:56:20 redsen-wordpress01 postfix/qmgr[2182]: 316CF2A1A19: from=<www-data@redsen-consulting.com>, size=716, nrcpt=1 (queue active)
Sep 22 20:56:20 redsen-wordpress01 postfix/local[2790]: 316CF2A1A19: to=<cfolliot@redsen-consulting.com>, relay=local, delay=0.15, delays=0.07/0.03/0/0.05, dsn=5.1.1, status=bounced (unknown user: "cfolliot")
Sep 22 20:56:20 redsen-wordpress01 postfix/cleanup[2788]: 51BF22A1A1B: message-id=<20150922205620.51BF22A1A1B@redsen-wordpress01>
Sep 22 20:56:20 redsen-wordpress01 postfix/bounce[2791]: 316CF2A1A19: sender non-delivery notification: 51BF22A1A1B
Sep 22 20:56:20 redsen-wordpress01 postfix/qmgr[2182]: 51BF22A1A1B: from=<>, size=2596, nrcpt=1 (queue active)
Sep 22 20:56:20 redsen-wordpress01 postfix/qmgr[2182]: 316CF2A1A19: removed
Sep 22 20:56:20 redsen-wordpress01 postfix/local[2790]: 51BF22A1A1B: to=<www-data@redsen-consulting.com>, relay=local, delay=0.12, delays=0.04/0/0/0.08, dsn=2.0.0, status=sent (delivered to mailbox)
Sep 22 20:56:20 redsen-wordpress01 postfix/qmgr[2182]: 51BF22A1A1B: removed
root@redsen-wordpress01:/var/log#

**Comment by szepeviktor** [comment]
@cedrox Could you use triple backquotes `` ` ``?

**Comment by szepeviktor** [comment]
Maybe `cfolliot@myDomain.com` is an invalid recipient.

**Comment by cedrox** [comment]
I finally use a really nice smtp plugin with O365 mail server : Postman SMTP.
Work with network. Log every communication. Multi provider...
Thanks everyone for your help !
